---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # # Flux-Kustomizations
  - ./common/ks.yaml
  # - ./bazarr/ks.yaml
  # - ./lidarr/ks.yaml
  # - ./overseerr/ks.yaml
  - ./plex/ks.yaml
  # - ./readarr/ks.yaml
  # - ./radarr/ks.yaml
  # - ./sonarr/ks.yaml
  # - ./tautulli/ks.yaml
  # - ./wizarr/ks.yaml

