---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
commonLabels:
  app.kubernetes.io/name: home-assistant
  app.kubernetes.io/instance: home-assistant
resources:
  - ./database.yaml
  - ./volsync.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./networkattachmentdefinition.yaml
patchesStrategicMerge:
  - ./patches/addons.yaml
