---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-volsync
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./kubernetes/apps/system/volsync/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: volsync
      namespace: system
  timeout: 3m

