---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dmahmalat
  namespace: flux-system
spec:
  interval: 30m
  url: oci://ghcr.io/dmahmalat/charts
  type: oci
  timeout: 3m
