---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # # Flux-Kustomizations
  - ./common/ks.yaml
  - ./bazarr/ks.yaml
  - ./music-assistant/ks.yaml
  - ./overseerr/ks.yaml
  - ./plex/ks.yaml
  - ./recyclarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./teddy-cloud/ks.yaml
  - ./tautulli/ks.yaml
  - ./unpackerr/ks.yaml
