---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization.yaml
metadata:
  name: secrets-emqx
  namespace: flux-system
  labels: 
    substitution.flux.home.arpa/enabled: "false"
spec:
  interval: 10m
  path: "./kubernetes/apps/home/emqx/secret"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: flux-emqx
      namespace: flux-system
  decryption:
    provider: sops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization.yaml
metadata:
  name: cluster-apps-emqx
  namespace: flux-system
  labels: 
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./kubernetes/apps/home/emqx/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  healthChecks:
    - apiVersion: helm.toolkt.fluxcd.io/v2beta1
      kind: HelmRelease
      name: emqx
      namespace: home
  dependsOn:
    - name: secrets-emqx
  postBuild:
    substituteFrom:
      - kind: Secret
        name: flux-home-assistant
        optional: false
