---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: starr-apps-secret
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: Vault
  target:
    name: starr-apps-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secrets/media/common/secret/starr-apps-secret
