---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: oci-terraform-authentik
  namespace: flux-system
spec:
  interval: 1m
  url: oci://ghcr.io/jefedavis/terraform/authentik
  ref:
    tag: main
