---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app internal-dns
  namespace: network
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/external-dns/
      chart: external-dns
      version: 1.14.5
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-external-dns
        namespace: flux-system
      interval: 30m
  values:
    fullnameOverride: *app

    sources:
      - crd
      - ingress
      - service

    podAnnotations:
      secret.reloader.stakater.com/reload: internal-dns-secret

    interval: 10s
    policy: sync
    registry: txt
    txtPrefix: "${CLUSTER_NAME}-"
    provider: rfc2136

    extraArgs:
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --rfc2136-host=${SYNOLOGY_ADDR}
      - --rfc2136-port=53
      - --rfc2136-zone=${INTERNAL_DOMAIN}
      - --rfc2136-zone=${EXTERNAL_DOMAIN}
      - --rfc2136-zone=${PROFESSIONAL_DOMAIN}
      - --rfc2136-tsig-axfr
      - --label-filter=internal-dns.home.arpa/disabled!=true

    serviceMonitor:
      enabled: true
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: internal-dns
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/envFrom
                value:
                  - secretRef:
                      name: internal-dns-secret
