---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-external-dns-crds
  namespace: flux-system
spec:
  targetNamespace: network
  path: "./kubernetes/apps/network/external-dns/crds"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom: []
  decryption:
    provider: sops
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-external-dns-internal
  namespace: flux-system
spec:
  targetNamespace: network
  path: "./kubernetes/apps/network/external-dns/internal"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom: []
  decryption:
    provider: sops
  dependsOn:
    - name: cluster-apps-kube-prometheus-stack-crds
    - name: cluster-apps-external-dns-crds
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-external-dns-external
  namespace: flux-system
spec:
  targetNamespace: network
  path: "./kubernetes/apps/network/external-dns/external"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom: []
  decryption:
    provider: sops
  dependsOn:
    - name: cluster-apps-kube-prometheus-stack-crds
    - name: cluster-apps-external-dns-crds
    - name: cluster-apps-dynamic-dns
    - name: cluster-apps-reflector
    - name: cluster-apps-cert-manager
