---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - ./external-certificate.yaml
  # - ./internal-certificate.yaml
  # - ./professional-certificate.yaml
  # - ./private-gateway.yaml
  - ./public-gateway.yaml
