---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public-gateway
  labels:
    networking.kubernetes.io/public-gateway: "true"
spec:
  gatewayClassName: envoy
  infrastructure:
    annotations:
      lbipam.cilium.io/ips: ${SVC_PUBLIC_GATEWAY_ADDR}
  listeners:
    - name: external-https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway.networking.k8s.io/shared-gateway-access: "true"
      tls:
        certificateRefs:
          - kind: Secret
            name: "wildcard-tls-external"
