---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://zebernst.github.io/synology-csi-talos
      chart: synology-csi
      version: 0.9.4
      sourceRef:
        kind: HelmRepository
        name: synology-csi
        namespace: flux-system
      interval: 30m
  values:
    clientInfoSecret:
      create: false
      name: synology-csi-secret
    images:
      attacher:
        image: registry.k8s.io/sig-storage/csi-attacher
        pullPolicy: IfNotPresent
        tag: v4.2.0
      nodeDriverRegistrar:
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar
        pullPolicy: IfNotPresent
        tag: v2.6.3
      plugin:
        image: ghcr.io/zebernst/synology-csi
        pullPolicy: IfNotPresent
        # Defaults to {{ $.Chart.AppVersion }} if empty or not present:
        tag: v1.1.2
      provisioner:
        image: registry.k8s.io/sig-storage/csi-provisioner
        pullPolicy: IfNotPresent
        tag: v3.4.0
      resizer:
        image: registry.k8s.io/sig-storage/csi-resizer
        pullPolicy: IfNotPresent
        tag: v1.7.0
      snapshotter:
        image: registry.k8s.io/sig-storage/csi-snapshotter
        pullPolicy: IfNotPresent
        tag: v6.2.1
    storageClasses:
      synology-iscsi-delete: 
        parameters:
          dsm: "${SYNOLOGY_ADDR}"
          fstype: ext4
          location: '/volume1'
          protocol: iscsi
      synology-iscsi-retain:
        parameters:
          dsm: "${SYNOLOGY_ADDR}"
          fstype: ext4
          location: '/volume1'
          protocol: iscsi
        isDefault: true
    volumeSnapshotClasses:
      synology-iscsi-delete:
        deletionPolicy: Delete
      synology-iscsi-retain:
        deletionPolicy: Retain
