---
apiVersion: v1
kind: Namespace
metadata:
  name: resume
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    gateway.networking.k8s.io/shared-gateway-access: "true"
    istio.io/dataplane-mode: ambient
