---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: resume
resources:
  - ./overview.yaml
  - ./certifications/certs.yaml
  - ./experience/20cs-usaf.yaml
  - ./experience/691cos-usaf.yaml
  - ./experience/epic.yaml
  - ./experience/vmware.yaml
