apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-branding
  namespace: security
binaryData:
  davishaus-favicon.png: iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAdgAAAHYBTnsmCAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAANjSURBVDiNfZJbaNtlAMXP9/3z5f5vmtgkTdqkXbfVrg7dVjqqWzexU7aHKoPVsVIU9iAqDCbIhjcobhTmXpwgeNvDXlQ2LYrQeVldBzK3dc6qq3apveTSNGka2zT//i9J/t/nW5EqnsfD4cc5cAj+Q7kTZ2Tdyd8VRvmQoCCwWT9zcP2FQH+/sj5L1hui56KU3BIbobW17Y4Dj1uFEEQfvsZFev5G/d2mPeTS0+Y/83Q9INX65wDx+XZ4ents9259JyZuX0H14YNUBPztiZbYwP82SPQPPAnQT1zPHnHEfr5mxkdHLAAQbetEy859UD4d1Imi9kXefOXzfwGSr5/azEF+snXvt+kOYhkf/oI+2N0HIQTGvryArV0H4TIZN4a+0XiJtDeePvnH2oTMy2ddgvMha9tDtKq1hd28+D4NPdAGl9cPty+AUMs23B48D3fzJmrZvs1KROly7sQZeQ1Qspc+IuFwjbtrr2Po7VeJRCgSoyNYTs9iaW4GqTs/gAK4fO41yJ0djIaCfo0ZFwBAir9x+jiY5Tn5mcPy+NWv6HJiEnaXGyVVQX5qHJnf76BS0mFzulFaVWAYOsIHui3G2N26l3bv1S1EkF5nz1MOaBqRvb7cI33HbN66RqdeLJRz0xNFgBD/xi2y3S1b8slpdTmTKpkV4z7noW6X/vHgESKEoNl3PpjWtWIk11pP83MzUBfnQZgVwc1bAS6QnfwNnJuQa0KoDjegXvIKJOZ+DT1/dDslhHCya+e3UlNDavbWMCrFv0C4CQYCu80BJkmg3AQ1Kyit5BEfvYpyPFGoeuKxc4QQQQHAzGW+dgRDbrfPD62wBInZ0NF7DBHhwaZgM/YcPQlCJWiFJXgC9XA92impqfkxACCqqkYkzndnTp19b6FBllWHRHyN9yM4p0C/NwlQAnn/PkzNT2C1sAhfUcBTqFRqjr/YB0m6TpSiEmeMRbWJ2CrbuMFlYQzZ2RjYlRsAYyin03B2tEPfUAt/YzME59CSqaKzISoDmLR8/+Fb9ura8OxKLiusN512q91ebnq4ixAgUs5m1m5e0rTYj5fO201dlTRVQVUglFfyWWbJJ2KelfRMgHOxAMH9VJJIdMeupGRWTGGUKYRAZXHRNLyMpX65HiUgKFfMheXkVB0FNf4Gh/d3WVw/BawAAAAASUVORK5CYII=
data:
  davishaus-logo.svg: <svg id="Capa_1" enable-background="new 0 0 497.023 497.023"
    height="512" viewBox="0 0 497.023 497.023" width="512" xmlns="http://www.w3.org/2000/svg"><g><path
    d="m101.755 436.022-34.74-159.01h363.135l-26.65 159.01z" fill="#ab7b64"/><path
    d="m430.15 277.012-4.19 24.99c-3.26.82-7.16 1.81-11.84 2.98l-2.2.55c-6.91 1.74-13.36
    2.48-21.55 2.48-20.38 0-31.08-4.81-40.52-9.05-8.29-3.73-15.45-6.95-30.68-6.95-15.22
    0-22.38 3.22-30.67 6.94-9.44 4.25-20.14 9.06-40.51 9.06s-31.07-4.81-40.51-9.06c-8.29-3.72-15.45-6.94-30.67-6.94-15.23
    0-22.38 3.22-30.67 6.94-9.44 4.25-20.14 9.06-40.51 9.06-5.71 0-10.86-.37-15.74-1.12-.86-.12-7.68-1-14.27-1.86-.88-.11-1.73-.22-2.55-.33l-6.05-27.69z"
    fill="#9a6a53"/><g><path d="m449.94 313.062-8.23 40.6-21.444 14.38-25.156 8.91
    7.667-19.568.783-21.672 21.046-13.2z" fill="#f9f8f9"/><path d="m456.74 279.512-3.41
    11.574-.459 7.516-2.931 14.46-46.38 22.65 9.685-28.754 4.925-42.546z" fill="#e27f86"/><path
    d="m441.71 353.662-16.7 82.35-42.74 3.61 11.698-36.919 1.142-25.751z" fill="#e27f86"/><path
    d="m421.34 327.032-8.4 41.01-9.38 9.64-8.45-.73 8.45-41.24 7.387-6.286z" fill="#e8e8e8"/><g
    fill="#df646e"><path d="m412.94 368.042-14.39 70.2-16.28 1.38 12.84-62.67z"/><path
    d="m418.17 264.412-5 24.4-9.61 46.9 17.78-8.68 5.399-26.354c.355-1.733 2.115-2.753
    3.815-2.267 2.148.614 4.37 1.079 6.656 1.381 1.37.18 2.81.27 4.29.27 3.44 0 7.231-.49
    11.371-1.46l3.869-19.09z"/></g></g><path d="m42.981 273.384h416.221l-199.915-248.936z"
    fill="#ab7b64"/><path d="m459.2 273.382h-56.78c-1.005-2.512-1.767-5.142-2.26-7.869-.223-1.235-.388-2.49-.5-3.761-.207-2.394-.211-4.794-.018-7.171.082-1.009-.647-1.917-1.647-2.07-18.958-2.908-33.629-18.39-35.325-37.739-.215-2.404-.221-4.808-.027-7.192.082-1.008-.647-1.915-1.647-2.069-18.968-2.916-33.63-18.398-35.326-37.739-.215-2.404-.221-4.808-.027-7.192.082-1.009-.647-1.915-1.647-2.069-18.891-2.905-33.543-18.308-35.316-37.569-.232-2.492-.24-4.991-.033-7.466.087-1.037-.664-1.937-1.691-2.103-19.333-3.108-32.629-16.335-34.276-34.472-.08-.85-.14-1.75-.17-2.67-.08-2.14-1.84-3.81-4.01-3.81s-3.93
    1.67-4.01 3.81c-.03.92-.09 1.82-.17 2.67-1.647 18.136-14.952 31.364-34.276 34.472-1.027.165-1.778
    1.066-1.691 2.103.207 2.475.199 4.975-.033 7.476-1.773 19.251-16.425 34.654-35.316
    37.559-1 .154-1.729 1.06-1.647 2.069.193 2.384.187 4.788-.027 7.192-1.696 19.341-16.367
    34.823-35.326 37.739-1 .154-1.728 1.061-1.647 2.069.193 2.384.187 4.788-.027 7.192-1.696
    19.341-16.358 34.823-35.326 37.739-1 .154-1.728 1.061-1.646 2.07.193 2.377.189
    4.777-.018 7.171-.36 4.09-1.32 7.99-2.81 11.63h-51.55l216.31-248.93z" fill="#9a6a53"/><path
    d="m74.011 259.767c.849.23 13.085 4.167 13.95 4.372 2.08.494 5.479 2.309 5.479
    2.309l3.371-.832c2.595.255 5.48.395 8.816.395 35.59 0 35.59-16 71.181-16 35.592
    0 35.592 16 71.184 16 35.591 0 35.591-16 71.182-16 35.596 0 35.596 16 71.192 16
    3.763 0 6.95-.179 9.795-.499 0 0 2.975.395 3.4.339 3.321-.439 4.095-1.573 6.94-2.34l7.298-2.766
    21.66 25.489c-.281.076-10.276 1.484-18.681 3.596-1.388.349-3.788 2.056-3.788 2.056-4.454
    1.119-7.835 1.968-7.999 2.01-5.106 1.284-10.511 2.115-18.625 2.115-35.596 0-35.596-16-71.192-16-35.591
    0-35.591 16-71.182 16-35.592 0-35.592-16-71.184-16-35.59 0-35.59 16-71.181 16-5.389
    0-9.962-.367-13.966-.989-.891-.139-40.642-5.263-41.479-5.425z" fill="#f9f8f9"/><path
    d="m439.46 286.232c-.33.09-13.551 3.416-22.471 5.656-8.74-6.24-14.879-15.564-16.829-26.374
    3.88-.44 7.13-1.131 10.34-2.001l7.3-2.77z" fill="#e8e8e8"/><circle cx="248" cy="168.512"
    fill="#f9f8f9" r="37.5"/><g><g><path d="m285.5 168.512c0 2.57-.26 5.08-.75 7.5h-29.25v29.25c-2.42.49-4.93.75-7.5.75s-5.08-.26-7.5-.75v-29.25h-29.25c-.49-2.42-.75-4.93-.75-7.5s.26-5.08.75-7.5h29.25v-29.25c2.42-.49
    4.93-.75 7.5-.75s5.08.26 7.5.75v29.25h29.25c.49 2.42.75 4.93.75 7.5z" fill="#e8e8e8"/></g></g><g
    fill="#f9f8f9"><circle cx="178" cy="220.012" r="7.5"/><circle cx="247.947" cy="236.064"
    r="7.5"/><circle cx="318" cy="310.012" r="7.5"/><circle cx="358" cy="330.012"
    r="7.5"/><circle cx="178" cy="310.012" r="7.5"/><circle cx="138" cy="330.012"
    r="7.5"/><circle cx="318" cy="220.012" r="7.5"/></g><path d="m96.811 265.616c-2.14
    11.49-9.181 21.245-19.481 27.535-11.79-1.53-26.64-3.45-27.15-3.55l23.83-29.83c.85.23
    13.09 4.16 13.95 4.37 2.7.641 5.541 1.145 8.851 1.475z" fill="#e8e8e8"/><g><path
    d="m55.29 353.662v-.01l-.343-16.14-7.887-24.45 24.568 9.45 21.812 13.2 8.45 41.24-24.007-9.228z"
    fill="#f9f8f9"/><path d="m93.44 335.712-46.38-22.65v-12.1l-6.47-19.83 38.61-14.92.598
    14.746 3.951 7.454z" fill="#e27f86"/><path d="m114.19 436.972-42.68-3.3-3.116-38.355-13.104-41.655
    46.6 23.29v.01z" fill="#e27f86"/><path d="m55.29 353.662v-.01l-8.23-40.59h8.23l9.53
    8.67 6.47 31.92v.01l1.92 8.96h-9.072z" fill="#e8e8e8"/><g fill="#df646e"><path
    d="m88.71 435.002-17.2-1.33-16.22-80.01 17.92 8.96z"/><path d="m83.75 288.412-4.55-22.2-38.61
    14.92 3.62 17.87h.001l2.849 14.06 17.76 8.67c-.868-4.268-2.691-13.265-3.886-19.161-.32-1.578.668-3.099
    2.228-3.501 7.255-1.87 15.278-5.846 20.588-10.658z"/></g></g><path d="m22 277.012c6.62
    3.688 24.809 13.22 36.239 10.878 14.094-2.887 25.89-12.848 27.143-27.179.254-2.907.093-5.737-.43-8.437-1.126-5.807
    2.988-11.032 8.898-11.291.47-.021.942-.052 1.416-.095 14.315-1.283 25.858-12.849
    27.115-27.166.246-2.802.106-5.532-.372-8.143-1.1-6.01 2.737-11.328 8.841-11.596.47-.021.943-.052
    1.418-.095 14.314-1.284 25.857-12.849 27.114-27.166.246-2.802.106-5.532-.372-8.144-1.101-6.011
    2.737-11.327 8.842-11.596.453-.02.908-.05 1.365-.09 14.282-1.257 25.841-12.768
    27.153-27.045.263-2.862.123-5.649-.369-8.313-1.063-5.751 2.932-11.177 8.765-11.606.206-.015.413-.032.62-.052
    14.232-1.332 25.693-9.826 26.987-24.061.06-.657.101-1.34.127-2.037.321-8.581 7.413-15.355
    16-15.355 8.587 0 15.679 6.774 16 15.355.026.697.068 1.379.127 2.037 1.294 14.235
    12.756 22.729 26.987 24.061.207.019.414.037.62.052 5.833.429 9.828 5.854 8.765
    11.606-.492 2.664-.632 5.451-.369 8.313 1.313 14.277 12.872 25.788 27.153 27.045.457.04.912.07
    1.365.09 6.105.268 9.943 5.585 8.842 11.596-.478 2.612-.618 5.342-.372 8.144 1.257
    14.317 12.799 25.883 27.114 27.166.475.043.947.074 1.418.095 6.104.268 9.941 5.586
    8.841 11.596-.478 2.612-.618 5.342-.372 8.143 1.257 14.317 12.8 25.883 27.115
    27.166.474.043.946.074 1.416.095 5.91.259 10.024 5.484 8.898 11.291-.524 2.7-.685
    5.53-.43 8.437 1.253 14.332 12.878 25.315 27.143 27.179 11.407 1.49 29.356-7.3
    36.239-10.878l-182.777-251.032h-81.723z" fill="#f9f8f9"/><path d="m22 277.012-5.33-4.09-6.685-1.419c-8.174-4.323-10.569-15.073-4.792-22.477l164.163-210.384c19.023-24.379
    48.221-38.63 79.144-38.63 30.923 0 60.12 14.252 79.144 38.631l164.162 210.383c5.727
    7.34 3.424 17.967-4.578 22.362l-6.919 1.06-5.309 4.564-173.944-221.427c-12.661-16.144-32.04-25.573-52.556-25.573-20.517
    0-39.895 9.429-52.556 25.573z" fill="#e27f86"/><g><path d="m411.773 440.892 2.59
    25.641-2.59 29.479h-74.25c-5.52 0-10-4.48-10-10v-45.11c5.91 3.5 23.26 13.43 41.62
    13.43 18.37 0 36.73-9.94 42.63-13.44z" fill="#ab7b64"/><path d="m411.773 434.132v6.76c-5.9
    3.5-24.255 15.216-42.625 15.216-10.697 0-21.829-3.133-30.061-6.638l-11.851-8.915v-6.511c0-13.245
    5.842-24.8 15.319-32.617 1.326-1.093 3.657-3.227 3.657-3.227 6.621-4.234 14.489-6.688
    22.931-6.688h.01c23.54 0 42.62 19.08 42.62 42.62z" fill="#f9f8f9"/><path d="m346.213
    398.202c-4.24 6.62-6.69 14.49-6.69 22.93v26.32l-7.117-1.153-5.883-5.397v-6.77c0-15.1
    7.85-28.36 19.69-35.93z" fill="#e8e8e8"/><path d="m369.143 467.332c16.66 0 32.74-6.57
    42.63-11.61l2.59-6.678-2.59-8.152c-5.9 3.5-24.26 13.44-42.63 13.44-10.698 0-21.388-3.372-29.62-6.878v-.002c-5.9-2.51-10.53-5.09-13-6.55v14.82
    41.29h85.25l1.697-5.585-1.697-7.415h-66.25c-3.314 0-6-2.686-6-6v-13.734c0-1.371
    1.344-2.336 2.641-1.89 8.104 2.788 17.445 4.944 26.979 4.944z" fill="#9a6a53"/></g><g><path
    d="m497.023 440.892v45.12c0 5.523-4.477 10-10 10h-64.25c-5.523 0-10-4.477-10-10v-45.11c5.91
    3.5 23.26 13.43 41.62 13.43 18.37 0 36.73-9.94 42.63-13.44z" fill="#ab7b64"/><path
    d="m497.023 434.132v6.76c-5.9 3.5-24.255 15.216-42.625 15.216-10.697 0-21.829-3.133-30.061-6.638l-11.851-8.915v-6.511c0-13.245
    5.842-24.8 15.319-32.617 1.326-1.093 3.657-3.227 3.657-3.227 6.621-4.234 14.489-6.688
    22.931-6.688h.01c23.54 0 42.62 19.08 42.62 42.62z" fill="#f9f8f9"/><path d="m431.463
    398.202c-4.24 6.62-6.69 14.49-6.69 22.93v26.32l-7.117-1.153-5.883-5.397v-6.77c0-15.1
    7.85-28.36 19.69-35.93z" fill="#e8e8e8"/><path d="m454.393 467.332c16.66 0 32.74-6.57
    42.63-11.61v-14.83c-5.9 3.5-24.26 13.44-42.63 13.44-10.698 0-21.388-3.372-29.62-6.878v-.002c-5.9-2.51-10.53-5.09-13-6.55v14.82
    41.29h75.25c5.523 0 10-4.477 10-10v-3h-66.25c-3.314 0-6-2.686-6-6v-13.734c0-1.371
    1.344-2.336 2.641-1.89 8.104 2.788 17.445 4.944 26.979 4.944z" fill="#9a6a53"/></g><g><path
    d="m85.25 440.892 2.59 25.641-2.59 29.479h-74.25c-5.52 0-10-4.48-10-10v-45.11c5.91
    3.5 23.26 13.43 41.62 13.43 18.37 0 36.73-9.94 42.63-13.44z" fill="#ab7b64"/><path
    d="m85.25 434.132v6.76c-5.9 3.5-24.255 15.216-42.625 15.216-10.697 0-21.829-3.133-30.061-6.638l-11.851-8.915v-6.511c0-13.245
    5.842-24.8 15.319-32.617 1.326-1.093 3.657-3.227 3.657-3.227 6.621-4.234 14.489-6.688
    22.931-6.688h.01c23.54 0 42.62 19.08 42.62 42.62z" fill="#f9f8f9"/><path d="m19.69
    398.202c-4.24 6.62-6.69 14.49-6.69 22.93v26.32l-7.117-1.153-5.883-5.397v-6.77c0-15.1
    7.85-28.36 19.69-35.93z" fill="#e8e8e8"/><path d="m42.62 467.332c16.66 0 32.74-6.57
    42.63-11.61l2.59-6.678-2.59-8.152c-5.9 3.5-24.26 13.44-42.63 13.44-10.698 0-21.388-3.372-29.62-6.878v-.002c-5.9-2.51-10.53-5.09-13-6.55v14.82
    31.29c0 5.523 4.477 10 10 10h75.25l1.697-5.585-1.697-7.415h-66.25c-3.314 0-6-2.686-6-6v-13.734c0-1.371
    1.344-2.336 2.641-1.89 8.104 2.788 17.445 4.944 26.979 4.944z" fill="#9a6a53"/></g><g><path
    d="m170.494 440.892 2.59 25.641-2.59 29.479h-74.25c-5.52 0-10-4.48-10-10v-45.11c5.91
    3.5 23.26 13.43 41.62 13.43 18.37 0 36.73-9.94 42.63-13.44z" fill="#ab7b64"/><path
    d="m170.494 434.132v6.76c-5.9 3.5-24.255 15.216-42.625 15.216-10.697 0-21.829-3.133-30.061-6.638l-11.851-8.915v-6.511c0-13.245
    5.842-24.8 15.319-32.617 1.326-1.093 3.657-3.227 3.657-3.227 6.621-4.234 14.489-6.688
    22.931-6.688h.01c23.54 0 42.62 19.08 42.62 42.62z" fill="#f9f8f9"/><path d="m104.934
    398.202c-4.24 6.62-6.69 14.49-6.69 22.93v26.32l-7.117-1.153-5.883-5.397v-6.77c0-15.1
    7.85-28.36 19.69-35.93z" fill="#e8e8e8"/><path d="m127.864 467.332c16.66 0 32.74-6.57
    42.63-11.61l2.59-6.678-2.59-8.152c-5.9 3.5-24.26 13.44-42.63 13.44-10.698 0-21.388-3.372-29.62-6.878v-.002c-5.9-2.51-10.53-5.09-13-6.55v14.82
    41.29h85.25l1.697-5.585-1.697-7.415h-66.25c-3.314 0-6-2.686-6-6v-13.734c0-1.371
    1.344-2.336 2.641-1.89 8.104 2.788 17.445 4.944 26.979 4.944z" fill="#9a6a53"/></g><path
    d="m248.583 326.395c-43.078 0-75.593 34.89-75.593 77.968l-.638 90.51 154.149.511v-91.372c0-40.778-31.291-74.247-71.172-77.705-.001-.001-4.446.088-6.746.088z"
    fill="#f9f8f9"/><path d="m187.583 484.012c-1.657 0-3-1.343-3-3v-77c0-40.72 31.197-74.153
    70.997-77.683-2.258-.215-4.532-.312-6.837-.317-42.988-.082-78.16 35.779-78.16
    78.768v92.232h30.107l48.736-3.16 46.881 3.16h30.276v-13z" fill="#e8e8e8"/><path
    d="m248.5 356.203c-26.403 0-46.723 20.991-46.723 47.394l.383 91.787 44.957-2.17
    49.189 3.798v-93.352c0-24.111-17.849-44.052-41.054-47.333 0 0-1.931.064-2.827-.012-1.346-.114-2.549-.112-3.925-.112z"
    fill="#e27f86"/><path d="m217.69 484.012c-1.657 0-3-1.343-3-3v-77.35c0-24.02 17.73-43.91
    40.81-47.3-2.263-.337-4.584-.507-6.945-.51-26.328-.029-47.865 22.221-47.865 48.549v92.611h95.62v-13z"
    fill="#df646e"/><g><path d="m233 439.512c-4.143 0-7.5-3.358-7.5-7.5v-8c0-4.142
    3.357-7.5 7.5-7.5s7.5 3.358 7.5 7.5v8c0 4.142-3.357 7.5-7.5 7.5z" fill="#f9f8f9"/></g><g><path
    d="m248 213.512c-24.813 0-45-20.187-45-45s20.187-45 45-45 45 20.187 45 45-20.187
    45-45 45zm0-75c-16.542 0-30 13.458-30 30s13.458 30 30 30 30-13.458 30-30-13.458-30-30-30z"
    fill="#e8e8e8"/></g><path d="m475 277.012-13.05 6.05-171.9-218.83c-10.08-12.85-25.22-20.22-41.55-20.22s-31.47
    7.37-41.54 20.21l-172.11 219.1-12.85-6.31 164.19-218.656c15.305-20.382 39.308-32.374
    64.796-32.374 25.909 0 50.255 12.389 65.505 33.334z" fill="#e8e8e8"/><path d="m487.228
    271.388-12.228 5.624-173.94-221.43c-12.66-16.14-32.04-25.57-52.56-25.57-10.26
    0-20.24 2.36-29.23 6.73-8.99 4.38-17 10.77-23.33 18.84l-173.94 221.43-12.03-5.52
    175.74-223.93c15.23-19.41 38.12-30.55 62.79-30.55s47.56 11.14 62.78 30.54z" fill="#df646e"/></g></svg>