---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./descheduler/ks.yaml
  - ./intel-device-plugins/ks.yaml
  - ./kured/ks.yaml
  - ./kubelet-csr-approver/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./reloader/ks.yaml
  - ./reflector/ks.yaml
  - ./system-upgrade-controller/ks.yaml

