---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  # - ./blocky/ks.yaml
  # - ./dynamic-dns/ks.yaml
  # - ./external-dns/ks.yaml
  # - ./pod-gateway/ks.yaml
  - ./smtp-relay/ks.yaml
  # - ./multus/ks.yaml
  - ./external-services/ks.yaml
