---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/resumes.jefedavis.dev_profiles.yaml
  - bases/resumes.jefedavis.dev_jobexperiences.yaml
  - bases/resumes.jefedavis.dev_certifications.yaml

configurations:
  - kustomizeconfig.yaml
